### PR TITLE
add minified version

### PR DESCRIPTION
**Pull request by thib3113**

### CODE REVIEW

**Comment by eparziale** [comment]
@thib3113  Any particular reason why the minified version hasn't been merged into master yet?

**Comment by thib3113** [comment]
No idea, I forgot this pull request . 

Maybe this repo is abandoned

**Comment by leongersen** [comment]
It's not, I'll try to get this cleared up before the end of the month.

**Comment by leongersen** [comment]
I've added a minified version now. Sorry it took forever ;)

**Pull request closed without merging**
